# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Topic

# Model Form Field configuration
form: $/pensoft/courses/models/topic/fields.yaml

# Model Class name
modelClass: Pensoft\Courses\Models\Topic

# Default redirect location
defaultRedirect: pensoft/courses/topic

# Create page
create:
    title: backend::lang.form.create_title
    redirect: pensoft/courses/topic/update/:id
    redirectClose: pensoft/courses/topic

# Update page
update:
    title: backend::lang.form.update_title
    redirect: pensoft/courses/topic
    redirectClose: pensoft/courses/topic

# Preview page
preview:
    title: backend::lang.form.preview_title
