# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Lesson

# Model Form Field configuration
form: $/pensoft/courses/models/lesson/fields.yaml

# Model Class name
modelClass: Pensoft\Courses\Models\Lesson

# Default redirect location
defaultRedirect: pensoft/courses/lesson

# Create page
create:
    title: backend::lang.form.create_title
    redirect: pensoft/courses/lesson/update/:id
    redirectClose: pensoft/courses/lesson

# Update page
update:
    title: backend::lang.form.update_title
    redirect: pensoft/courses/lesson
    redirectClose: pensoft/courses/lesson

# Preview page
preview:
    title: backend::lang.form.preview_title
