materials:
    label: Material
    view:
        list: $/pensoft/courses/models/material/columns.yaml
        toolbarButtons: create|delete
        recordsPerPage: 10
        showCheckboxes: true
        showSorting: true
        defaultSort: sort_order asc
    manage:
        form: $/pensoft/courses/models/material/fields.yaml
        recordsPerPage: 10
        showCheckboxes: true
        recordOnClick: true
    deferredBinding: true 