# ===================================
#  List Behavior Config
# ===================================

list: $/pensoft/courses/models/topic/columns.yaml
modelClass: Pensoft\Courses\Models\Topic
customViewPath: $/pensoft/courses/controllers/topics
title: Manage Topics

noRecordsMessage: backend::lang.list.no_records

recordsPerPage: 20

showSetup: true
showCheckboxes: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt

recordUrl: pensoft/courses/topics/update/:id 