# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Block

# Model Form Field configuration
form: $/pensoft/courses/models/block/fields.yaml

# Model Class name
modelClass: Pensoft\Courses\Models\Block

# Default redirect location
defaultRedirect: pensoft/courses/block

# Create page
create:
    title: backend::lang.form.create_title
    redirect: pensoft/courses/block/update/:id
    redirectClose: pensoft/courses/block

# Update page
update:
    title: backend::lang.form.update_title
    redirect: pensoft/courses/block
    redirectClose: pensoft/courses/block

# Preview page
preview:
    title: backend::lang.form.preview_title
