# ===================================
#  Form Behavior Config
# ===================================

name: Setting
form: $/pensoft/courses/models/setting/fields.yaml
modelClass: Pensoft\Courses\Models\Setting
defaultRedirect: pensoft/courses/settings

create:
    redirect: pensoft/courses/settings/update/:id
    redirectClose: '{{ backUrl|default("pensoft/courses/settings") }}'

createLevel:
    title: Create Block Level
    redirect: pensoft/courses/settings/update/:id
    redirectClose: pensoft/courses/settings/levels

createMaterialType:
    title: Create Material Type
    redirect: pensoft/courses/settings/update/:id
    redirectClose: pensoft/courses/settings/materialtypes

update:
    redirect: '{{ backUrl|default("pensoft/courses/settings") }}'
    redirectClose: '{{ backUrl|default("pensoft/courses/settings") }}'

preview:
    redirect: '{{ backUrl|default("pensoft/courses/settings") }}' 