# ===================================
#  List Behavior Config - Material Types
# ===================================

list: $/pensoft/courses/models/setting/columns_materialtypes.yaml
modelClass: Pensoft\Courses\Models\Setting
title: Manage Material Types

noRecordsMessage: No material types found

recordsPerPage: 20

showSetup: true
showCheckboxes: true

filter:
    scopes:
        material_types:
            label: Material Types
            modelScope: materialTypes

toolbar:
    buttons: list_toolbar_materialtypes
    search:
        prompt: Search material types...

recordUrl: pensoft/courses/settings/update/:id

defaultSort:
    column: sort_order
    direction: asc 