# ===================================
#  List Behavior Config - Block Levels
# ===================================

list: $/pensoft/courses/models/setting/columns_levels.yaml
modelClass: Pensoft\Courses\Models\Setting
title: Manage Block Levels

noRecordsMessage: No block levels found

recordsPerPage: 20

showSetup: true
showCheckboxes: true

filter:
    scopes:
        block_levels:
            label: Block Levels
            modelScope: blockLevels

toolbar:
    buttons: list_toolbar_levels
    search:
        prompt: Search block levels...

recordUrl: pensoft/courses/settings/update/:id

defaultSort:
    column: sort_order
    direction: asc 